### ISSUE TITLE
圖表編號問題

### ISSUE THREAD

**Issue by northsaga** [borting/nctu-thesis#8]
交大中文論文格式要求圖和表的編號要不分章節連續編號

請問如何修改?

**Comment by borting** [comment]
你可以在 main.tex 中加入 
`\renewcommand{\thefigure}{\arabic{figure}}`
試試看.

之前有和學校討論過, 正確的作法應該是分章節編號, 也比較符合一般 report/book 的編號方式.
但如果你的指導老師要求你這麼做 ... 就照做吧 XD

**Comment by northsaga** [comment]
感謝!!
