### ISSUE TITLE
羅馬數字頁碼起始點錯誤

### ISSUE THREAD

**Issue by Boteium** [borting/nctu-thesis#9]
摘要的頁碼不是從 i 開始，而是從 v 開始
目前採取的修正方法是註釋掉 thesis.cls 中 abstract 前的所有頁面 (如 copyright/title page)
然後再另外手動插入 pdf 中

**Comment by borting** [comment]
Hi ~ 對一本書來說, 翻開封面的那一頁就要開始編號, 所以 title page 才是第 i 頁喔.
你可以翻一下你手邊的原文書, 開始有頁碼 (通常是頁碼) 的也不會是第 i 頁喔 :P

**Comment by iblislin** [comment]
可是這樣上傳圖書館的審核不會通過

**Comment by iblislin** [comment]
我這裡被退，要求摘要才是 i

**Comment by Boteium** [comment]
我知道 latex 這樣標是一般情況
可是學校就是要求 abstract 從 i 開始

p.s. 授權書，審定書這些東西也是各院要求不同
這樣一來，各院的論文開始頁碼也會不一樣

**Comment by borting** [comment]
@iblis17 @Boteium 你們都是今年被退的嗎? 會不會是今年開始圖書館審查變嚴格了?
我去年上傳圖書館的時候都沒有這個問題 ... 實驗室的其他人也都沒有遇到 ...

我再找時間寫個 work around 的 option ... (上班族時間不多請見諒)

p.s. @Boteium 電機院這邊記得碩論是中文授權書/審定書各一張, 博論的話是再加一張英文審定書
請問你的院系要求是???

**Comment by borting** [comment]
BTW, 去年離校前, 跟教務處溝通過幾次.
教務處說他們的論文格式只是建議, 以院系自己規定為主. 但翻翻各院系網站的畢業規範也都說請參考教務處的規定 ... 簡直是個羅生門阿 XD
所以, @iblis17 @Boteium 兩位如果還在學的話, 可否幫忙跟圖書館+教務處討論一下
請他們討論出一個論文格式標準來 ...

**Comment by iblislin** [comment]
@borting 是的，我是上禮拜上傳的。

**Comment by borting** [comment]
It seems that NCTU Library also criticized on the copyright page ...
(info from my research group ...)

**Comment by borting** [comment]
@Boteium @iblis17
I think the problem is resolved in [v2.6](https://github.com/borting/nctu-thesis/releases/tag/v2.6) (tested under Ubuntu 16.04 w/ TeX Live 2015).
Please take it a try.
If there still has any problem, feel free to contact me or send an issue.
